# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91c6daa4e17a434a1609c8a7781a9238c4d7c2b017f6123facd0b80d6e25dde297951ff651ca5ee2f45e99a6314f4f76ebd4e5cf7f3e40ebe105ea207e146129

test:
  secret_key_base: ce92eca8e31f573742d1714371b3e55741497d9bdc1044e9b21d09ccbb5964a6a9d6daf51e055f5b8bd73156c774c16b6632d2dc5c6d54a6fb181fd491025ea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
